package org.venus.octopus.api.tool;

import java.util.Map;

/**
 * Tool interface.
 * <p>
 * Unified interface for tools that can be called by an Agent. A tool
 * encapsulates specific external capabilities (such as search, calculation,
 * HTTP requests, etc.), describes itself to the LLM via {@link ToolSpec}, and
 * the LLM generates calling parameters based on the ToolSpec.
 * </p>
 */
public interface Tool {

    /**
     * Gets the tool name (globally unique identifier).
     */
    String getName();

    /**
     * Gets the tool specification description (used to generate LLM function
     * calling configuration).
     */
    ToolSpec getSpec();

    /**
     * Executes the tool.
     *
     * @param args
     *            Parameters generated by the LLM, where key is the parameter name
     *            and value is the parameter value
     * @return The execution result of the tool (string format, which will be
     *         returned to the LLM as ToolMessage content)
     * @throws org.venus.octopus.common.exception.ToolException
     *             If execution fails
     */
    String execute(Map<String, Object> args);
}
