package org.venus.octopus.core.graph;

import java.util.*;
import org.venus.octopus.api.agent.AgentState;
import org.venus.octopus.api.graph.Graph;
import org.venus.octopus.common.exception.GraphException;

/**
 * Graph structure definition (read-only description of the graph structure).
 * <p>
 * Stores the node table and edge table of the graph. It is an intermediate
 * product after building StateGraph, generated by {@link StateGraph#compile()}
 * and then passed to CompiledGraphImpl.
 * </p>
 *
 * @param <S>
 *            AgentState type
 */
public class GraphDefinition<S extends AgentState> {

    /** Node table: node name -> node wrapper */
    private final Map<String, GraphNode<S>> nodes;

    /**
     * Edge table: source node name -> edge list (a source node can have multiple
     * edges, but only one direct edge)
     */
    private final Map<String, List<GraphEdge<S>>> edges;

    /** Entry point node name (the first node starting from START) */
    private String entryPoint;

    public GraphDefinition() {
        this.nodes = new LinkedHashMap<>();
        this.edges = new LinkedHashMap<>();
    }

    /**
     * Registers a node (called only during the graph construction phase).
     */
    public void registerNode(GraphNode<S> node) {
        String name = node.getName();
        if (nodes.containsKey(name)) {
            throw new GraphException("Node '" + name + "' already exists, node name must be unique");
        }
        nodes.put(name, node);
    }

    /**
     * Registers an edge (called only during the graph construction phase).
     */
    public void registerEdge(GraphEdge<S> edge) {
        String source = edge.getSource();
        edges.computeIfAbsent(source, k -> new ArrayList<>()).add(edge);

        // Identify the entry point node
        if (Graph.START.equals(source) && edge.isDirect()) {
            // Set the entry point directly via addEdge(START, xxx)
        }
    }

    /**
     * Validates the integrity of the graph structure.
     */
    public void validate() {
        List<GraphEdge<S>> startEdges = edges.get(Graph.START);
        if (startEdges == null || startEdges.isEmpty()) {
            throw new GraphException(
                    "The graph is missing an entry edge, please call addEdge(Graph.START, firstNode) to set the entry point");
        }

        // Validates that all nodes referenced by edges are registered
        for (Map.Entry<String, List<GraphEdge<S>>> entry : edges.entrySet()) {
            String source = entry.getKey();
            if (!Graph.START.equals(source) && !nodes.containsKey(source)) {
                throw new GraphException("Edge source node '" + source + "' is not registered");
            }
        }
    }

    public Map<String, GraphNode<S>> getNodes() {
        return Collections.unmodifiableMap(nodes);
    }

    public Map<String, List<GraphEdge<S>>> getEdges() {
        return Collections.unmodifiableMap(edges);
    }

    /**
     * Gets the next edge(s) for the specified node.
     *
     * @param nodeName
     *            Node name
     * @return Edge list (may be empty or contain only one)
     */
    public List<GraphEdge<S>> getEdgesFrom(String nodeName) {
        return edges.getOrDefault(nodeName, List.of());
    }

    /**
     * Gets a node by name.
     */
    public GraphNode<S> getNode(String name) {
        return nodes.get(name);
    }
}
